# Generated by Django 4.1 on 2022-10-31 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileName', models.CharField(max_length=50)),
                ('profileImage', models.URLField()),
                ('profileDescription', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('iamgeUrl', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('projectName', models.CharField(max_length=50)),
                ('projectGist', models.TextField()),
                ('projectDescription', models.TextField()),
            ],
        ),
    ]
