# Generated by Django 4.1 on 2022-11-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdetails',
            name='iamgeUrl',
        ),
        migrations.AddField(
            model_name='postdetails',
            name='imageUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
