# Generated by Django 4.1 on 2022-11-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_remove_postdetails_iamgeurl_postdetails_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='imageUrl',
            field=models.TextField(),
        ),
    ]
